회칙 개정 초안 (23.02.27.)
sparcs-kaist/sparcs.org-v3 pull request #25
Opened 2023-02-27 11:49 UTC by sboh1214

2023-02-27 13:04 UTC, withSang reviewed
LGTM 👍

2023-03-21 15:54 UTC, UrWrstNightmare commented on docs/rules/disciplinary/index.md
> +4. 제1항 및 제2항의 규정에 의하여 위원이 그 직무를 행할 수 없게 된 때에는 위원장이 지정하는 예비위원이 그 직무를 대행한다.
이사회가 대량 기피 (징계사유와 관계가 있어) 하면 어떻게 되나요?

2023-03-21 15:55 UTC, UrWrstNightmare commented on docs/rules/disciplinary/index.md
> +8. 경고: 징계위원회가 징계혐의자에게 경고를 한다.
사회봉사 같은거 추가 어떤가용

2023-03-21 15:57 UTC, UrWrstNightmare commented on docs/rules/disciplinary/index.md
> +이사회는 징계의결서를 받은 날로부터 10일이내에 이를 집행하여야 한다.
징계가 집행이 되지 않거나
당사자가 징계에 해당하는 내용을 행하지 않은 경우를 명시한 것이 있나요?

2023-03-21 15:58 UTC, SnowSuno commented on docs/rules/disciplinary/index.md
> +4. 보직 해임: 임원, PM, 위원장 또는 이에 상응하는 하나 이상의 직위에서 해임한다.
휠 자격 박탈도 들어가야 할거같은데 어디에 어떻게 들어가야 할지는 모르겠네요

2023-03-21 16:00 UTC, UrWrstNightmare commented on docs/rules/disciplinary/index.md
> +징계위원회에 참여한 자는 직무상 알게 된 비밀을 누설하여서는 아니된다.
임원진 전원이 징계위원회를 참여할 수 있는 것이 아닌데 (최대 4명?)
만약에 추후 업무 수행을 위해 해당 징계가 내려진 context를 알아야 할 경우에는 아에 알 수 있는 방법이 없는 건가요

2023-03-21 16:00 UTC, SnowSuno commented on docs/rules/disciplinary/index.md
> +1. 징계위원회의 위원중 징계혐의자의 친족 또는 직근상급자나 그 징계사유와 관계가 있는 자는 그 징계사건의 심의에 관여하지 못한다.
휠 회원 징계에 휠장은 관여하지 못하나요?

2023-03-21 16:02 UTC, ninesens commented on docs/rules/disciplinary/index.md
> +8. 경고: 징계위원회가 징계혐의자에게 경고를 한다.
경고 누적 시에 대해 규정하는 조항은 없어도 될까요?

2023-03-21 16:05 UTC, injoonH commented on docs/rules/disciplinary/index.md
> +8. 경고: 징계위원회가 징계혐의자에게 경고를 한다.
경고는 아무 효력이 없는지?

2023-03-21 16:05 UTC, injoonH commented on docs/rules/disciplinary/index.md
> +징계위원회에 참여한 자는 직무상 알게 된 비밀을 누설하여서는 아니된다.
비밀 누설 시 처벌?

2023-03-21 16:08 UTC, sboh1214 commented on docs/rules/disciplinary/index.md
> +이 규칙은 SPARCS 회칙(이하 “회칙”이라 한다) 제81조의 규정에 의한 징계위원회의 설치ㆍ종류ㆍ구성ㆍ권한ㆍ심의절차 및 징계대상자의 진술에 관한 사항을 정함을 목적으로 한다.
직무 정지 조항 신설

2023-03-21 16:22 UTC, ninesens commented on docs/rules/disciplinary/index.md
>  징계위원회는 징계의결요구서를 접수한 날로부터 30일이내에 징계에 관한 의결을 하여야 한다. 단 부득이한 사유가 있을 때에는 당해징계위원회의 의결로 30일에 한하여 그 기간을 연장할 수 있다.
근데 의결을 부득이하게 미루는데 의결로 연장하는 건 좀 모순적이네

2023-03-21 16:25 UTC, sboh1214 commented on docs/rules/disciplinary/index.md
> +5. 징계혐의자의 소재가 분명하지 아니할 때에는 제3항의 출석통지는 단체 회원들이 자유롭게 볼 수 있는 곳에 게재한 날로부터 10일이 경과하면 그 출석통지서가 송달된 것으로 본다.
"준회원과 정회원"

2023-03-21 16:39 UTC, 0ev commented on docs/rules/disciplinary/index.md
> +이사회는 징계의결서를 받은 날로부터 10일이내에 이를 집행하여야 한다.
방학 이슈는 어떻게 할까요

2023-03-21 16:49 UTC, sboh1214 commented on docs/rules/disciplinary/index.md
> +4. 보직 해임: 임원, PM, 위원장 또는 이에 상응하는 하나 이상의 직위에서 해임한다.
보직 해임 및 자격 박탈

2023-03-28 14:52 UTC, sboh1214 commented on docs/rules/disciplinary/index.md
> +1. 징계위원회의 위원중 징계혐의자의 친족 또는 직근상급자나 그 징계사유와 관계가 있는 자는 그 징계사건의 심의에 관여하지 못한다.
위원장 유고시 또는 위원장에 대한 기피 인용시에는 위원장이 미리 지정한 위원이 그 직무를 대행한다.

2023-03-28 16:20 UTC, sboh1214 commented on docs/rules/disciplinary/index.md
> +8. 경고: 징계위원회가 징계혐의자에게 경고를 한다.
기존의 제명안의 경고 대체와 같이 징계혐의자가 이행하지 않을 경우 재 징계할 수 있도록 수정

2023-03-28 16:20 UTC, sboh1214 commented on docs/rules/disciplinary/index.md
> +8. 경고: 징계위원회가 징계혐의자에게 경고를 한다.
너무 복잡해용~

2023-03-28 16:21 UTC, sboh1214 commented on docs/rules/disciplinary/index.md
> +이사회는 징계의결서를 받은 날로부터 10일이내에 이를 집행하여야 한다.
온라인 매체를 이용한 통고가 제한되지는 않습니다

2023-03-28 16:21 UTC, sboh1214 commented on docs/rules/disciplinary/index.md
> +징계위원회에 참여한 자는 직무상 알게 된 비밀을 누설하여서는 아니된다.
징계의결서로 충분할 것으로 판단됩니다

2023-03-28 16:31 UTC, sboh1214 commented on docs/rules/disciplinary/index.md
> +징계위원회에 참여한 자는 직무상 알게 된 비밀을 누설하여서는 아니된다.
회칙에 추가하였습니다

2023-03-28 16:32 UTC, sboh1214 commented on docs/rules/disciplinary/index.md
> +징계위원회에 참여한 자는 직무상 알게 된 비밀을 누설하여서는 아니된다.
단순히 알게 된 정보라고 지칭할 시 범위가 지나치게 넓어질 가능성이 있습니다.

2023-03-28 16:34 UTC, sboh1214 commented on docs/rules/disciplinary/index.md
> +2. 위원장에는 회장이 되고 위원은 임원진 2인 이상을 포함한 정회원 중에서 위원장이 지명한다.
적절한 어구를 생각해 내지 못하였음

2023-03-29 04:32 UTC, 0ev requested changes

2023-03-29 04:32 UTC, 0ev commented on docs/rules/disciplinary/index.md
문제사항들이 잘 해결된 것 같아요!

2023-03-29 04:32 UTC, 0ev commented on docs/rules/wheel/index.md
좋은거 같아요!

2023-03-29 04:32 UTC, 0ev commented on docs/rules/index.md
일단 수정사항이랑 번호 바뀐것만 체크해보았는데 좋은거 같아요! 오늘 수업 모두 끝나고 전체 다시 한번 읽어보겠습니다

2023-03-29 04:32 UTC, 0ev commented on docs/rules/design/index.md
> +1. 디자인팀은 SPARCS의 브랜딩 및 SPARCS에서 운영하는 서비스의 디자인 관련 사안을 다룬다.
👍

2023-03-29 04:32 UTC, 0ev commented on docs/rules/design/index.md
>  1. 디자인 피드백은 디자이너가 독단적으로 작업하지 않으며, 타 디자이너들과의 협의를 통해 실제 런칭될 각 프로젝트의 디자인 완성도를 증진시키고 디자이너의 작업 부담을 줄이는 것을 목적으로 한다.
굳이 "런칭될" 을 쓴 이유가 뭔가요? 출시될로 바꾸는게 낫지 않을까요?

2023-03-31 09:43 UTC, merged