Reorganize overall content and update some content
sparcs-kaist/sparcs.org-v3 pull request #33
Opened 2023-04-21 05:38 UTC by JeukHwang

2023-04-21 05:40 UTC, JeukHwang commented
전반적으로 변경 사항이 많아서 commit 보기 전에 로컬 서버 열어서 전반적인 변경 사항을 확인하시길 추천드려요

2023-04-21 05:40 UTC, JeukHwang commented
CI는 왜 실패하는거죠...?

2023-04-21 15:59 UTC, sboh1214 commented
@JeukHwang 
Build 성공 후 다시 요청해 주세요.
에러 메세지 가보면 원인 있습니다. (/docs/activities 페이지에서 깨진 링크 있음 seminar에 s가 없네요)

```
- On source page path = /docs/activities:
   -> linking to ./seminar (resolved as: /docs/seminar)
```

2023-04-24 01:58 UTC, 0ev approved these changes
LGTM

2023-04-24 01:58 UTC, 0ev commented on docusaurus.config.js
이거 순서 뒤집는 코드인데 없애면 문제생기지 않나요?

2023-04-24 01:58 UTC, 0ev commented on sidebars.js
아 여기서 손으로 작성했군요

2023-04-25 06:33 UTC, JeukHwang commented
> @JeukHwang Build 성공 후 다시 요청해 주세요. 에러 메세지 가보면 원인 있습니다. (/docs/activities 페이지에서 깨진 링크 있음 seminar에 s가 없네요)
> 
> ```
> - On source page path = /docs/activities:
>    -> linking to ./seminar (resolved as: /docs/seminar)
> ```

덕분에 해결했습니다 :)

2023-04-25 06:51 UTC, JeukHwang commented on sidebars.js
아뇨 그 두 개는 별개의 코드에요

위에는 seminar 2009, 2010, 2011을 역순으로 만드는 역할이었는데 수정 이후에 적용 방법을 몰라서 지웠어요
만약에 적용 방법 알면 조금만 도와주시면 감사하겠습니다 :(

2023-04-25 12:23 UTC, sboh1214 requested changes
혹시 Docusaurus 관하여 궁금하신 점 있다면 질문주시면 좋을 것 같습니다.

2023-04-25 12:23 UTC, sboh1214 commented on docs/activities.md
> +매주 월요일 오후 9시부터 한 시간 가량 [KAIST 교양분관(N11) 1층에 위치한 동아리방](https://goo.gl/maps/2PFRm87DKTTMyBXR8)에 모여 프로젝트 진행상황에 대한 이야기를 나눕니다. 또한 한 학기에 두 번 이상 모여 신입회원 승급 심사를 진행하고 단체의 중요한 일에 대해 논의합니다.
또한 제목이 정기모임/총회인 만큼 첫 문장에 정기모임, 두번째 문장에 총회라는 단어가 있으면 좋을 것 같기도 합니다.

2023-04-25 12:23 UTC, sboh1214 commented on docs/contact.md
> +구성원들이 모여 지내는 SPARCS 동방은 [KAIST 교양분관(N11) 1층](https://goo.gl/maps/2PFRm87DKTTMyBXR8)에 위치하고 있습니다.
마찬가지로, 네이버 맵, 카카오 맵, 구글 맵, 그리고 전체 주소를 차례로 제시하면 좋을 것 같습니다.

2023-04-25 12:23 UTC, sboh1214 commented on docs/index.md
> +우리를 위한 서비스를 만들기 위해, 한데 모였습니다.
"우리"가 자칫 동아리 구성원으로 비춰질 수 있을 것 같습니다. "모두"는 어떨까요

2023-04-25 12:23 UTC, sboh1214 commented on docs/index.md
> +원활한 서비스 개발/운영을 위해 매학기 개발자와 디자이너를 선발하고 있으며 이를 통해 [OTL](./projects/otl.md), [Ara](./projects/ara.md), [KAIST FTP](./projects/geoul.md) 등의 서비스를 안정적으로 운영하고 있습니다.
마찬가지로 절대경로~

2023-04-25 12:23 UTC, sboh1214 commented on docs/rules.md
> +SPARCS의 안정적인 운영을 위한 회칙으로 다음과 같이 이루어져 있습니다.
규칙 = 회칙 + 세칙 이 맞습니다.

본칙 > 회칙으로 변경해 주세요.

그리고 절대경로~

2023-04-25 12:23 UTC, sboh1214 commented on docs/rules/design/220829.md
> +sidebar_position: -1
0, 1, 2, ...
1, 2, 3, ...
으로 가는게 아니라 왜 -1이 나오죵?

2023-04-25 12:23 UTC, sboh1214 commented on docs/rules/design/index.md
> +# title: 2023년 4월 3일 개정
이 주석은 무엇을 의미하는건가요?

2023-04-25 12:23 UTC, sboh1214 commented on docusaurus.config.js
> +            to: "docs",
url을 docs/intro 로 해야될 것 같습니다.

2023-04-25 12:23 UTC, sboh1214 commented on sidebars.js
> +            // link: {
어떤 목적의 주석인가요?

2023-04-27 00:43 UTC, JeukHwang commented on docs/activities.md
> +## 프로젝트
개인적으로 쓸 때도 고민하던 바인데 이유가 있을까요?

2023-04-27 03:25 UTC, JeukHwang commented on docs/rules.md
> +SPARCS의 안정적인 운영을 위한 회칙으로 다음과 같이 이루어져 있습니다.
본칙이란 말은 여기 참고했어요
https://www.lawmaking.go.kr/lmKnlg/jdgStd/info?astSeq=95&astClsCd=CF0101

2023-04-27 03:26 UTC, JeukHwang commented on docs/rules/design/220829.md
> +sidebar_position: -1
역순으로 하되 새로운 게 추가되었을 때 기존 파일을 바꾸지 않기 위함이에요
공식 문서에서 float 지원하는 건 이미 확인해두었어요

2023-04-27 03:29 UTC, JeukHwang commented on docs/rules/design/index.md
> +# title: 2023년 4월 3일 개정
index.md에 적힌 sidebar_position: directory 순서
기타 파일에 적힌 sidebar_position: 해당 dir에서 파일 간 순서

따라서 새로운 개정안이 생겼을 때 기존 index.md에 적혀있던 내용은 어떤 metadata를 표시해야 하는지, 새롭게 생긴 index.md에는 어떤 metadata를 적어야 하는지 표시했어요

2023-04-27 05:51 UTC, JeukHwang commented on sidebars.js
> +            // link: {
sparcs.org/docs/projects에 해당되는 페이지는 수동 생성/자동 생성 모두 가능해요

자동 생성된 콘텐츠에서 추가하고 싶은 내용이 있어 수동 생성으로 자동 생성과 비슷한 형태를 만들었습니다.
주석 처리된 내용이 자동 생성용 코드입니다.

그 다음 수정할 사람도 docusaurus에 대해서 되게 잘 아는 건 아닐테니 일부러 넣어놨어요
설명을 더 달 걸 그랬나요

2023-04-27 05:53 UTC, JeukHwang commented on docs/activities.md
> +[SPARCS 2023 StartUp Hackathon 알아보기](https://bit.ly/SPARCS-2023-StartUp-Hackathon)
수정사항이 많아서 설명 추가하는 걸 잊었네요 :P 감사해요

2023-04-27 06:26 UTC, sboh1214 commented on docs/activities.md
> +## 프로젝트
@JeukHwang 
https://google.github.io/styleguide/docguide/style.html#add-spacing-to-headings

2023-04-27 06:32 UTC, sboh1214 commented on docs/rules.md
> +SPARCS의 안정적인 운영을 위한 회칙으로 다음과 같이 이루어져 있습니다.
@JeukHwang 
해당 법령입안심사기준은 하나의 법령에 대한 설명입니다.
회칙과 세칙은 각각 본문, 그리고 선택적으로 부칙 또는 별지 서식을 가지고 있는 법령(규칙)으로 보는 것이 타당합니다.
세칙을 회칙에서 분리시킨 것도 같은 이유입니다.

2023-04-27 06:36 UTC, sboh1214 commented on docs/rules/design/220829.md
> +sidebar_position: -1
단순히 역순으로 하기 위해서는 아래 기능을 사용하는 것이 나을 것 같습니다.

https://docusaurus.io/docs/sidebar/autogenerated#customize-the-sidebar-items-generator

2023-04-28 05:24 UTC, sboh1214 approved these changes
회칙 > 규칙, 본칙 > 회칙만 변경하면 될 듯합니다.
수고하셨어요 :)

2023-04-30 09:19 UTC, JeukHwang commented
@sboh1214 @0ev 리뷰 감사드려요 :)

2023-04-30 09:19 UTC, merged