Add better project explanations
sparcs-kaist/sparcs.org-v3 pull request #34
Opened 2023-04-30 09:28 UTC by JeukHwang

2023-04-30 17:21 UTC, sboh1214 approved these changes
LGTM

2023-04-30 22:11 UTC, 14KGun approved these changes
LGTM !

2023-05-01 17:26 UTC, sboh1214 requested changes
수고하셨습니다

2023-05-01 17:26 UTC, sboh1214 commented on .prettierrc
> +}
No new line at a end of file

2023-05-01 17:26 UTC, sboh1214 commented on .vscode/settings.json
> +}
.vscode/ 는 일반적으로 git에서 제외하는 것이 좋습니다.
formatting을 원한다면 pre-commit이나 husky를 찾아보세요

https://stackoverflow.com/questions/32964920/should-i-commit-the-vscode-folder-to-source-control

2023-05-01 17:26 UTC, sboh1214 commented on docs/projects/ara.md
> +## Member
준비중 이라고 써주면 좋을 것 같습니다

2023-05-01 17:26 UTC, sboh1214 commented on package.json
> +    "prettier": "^2.8.8",
prettier는 devDependencies 로 빠지는 것이 좋겠습니다

2023-05-02 14:10 UTC, withSang submitted a review, later dismissed
고생하셨습니다. :)

2023-05-04 04:19 UTC, 0ev approved these changes
진짜 엄청 많이 정리했네 ㄷㄷ LGTM!

2023-05-05 17:29 UTC, merged