update blog : gitops (230503)
sparcs-kaist/sparcs.org-v3 pull request #35
Opened 2023-05-03 10:06 UTC by cokia

Gitops 에 관한 블로그 글을 작성하였습니다.

2023-05-07 18:05 UTC, sboh1214 requested changes

2023-05-07 18:05 UTC, sboh1214 commented on blog/2023/index.md
> +slug: Gitops
소문자만 사용하여 gitops 로 변경해 주세요~ :)

2023-05-07 18:41 UTC, cokia commented
@sboh1214 수정하였습니다 감사합니다 :)

2023-08-18 02:54 UTC, sboh1214 approved these changes
LGTM

2023-08-18 03:01 UTC, merged