blog: Terraform Basics
sparcs-kaist/sparcs.org-v3 pull request #37
Opened 2023-05-03 15:13 UTC by xMHW

Terraform Basic 블로그 글입니다.

2023-05-08 04:58 UTC, JeukHwang requested changes
이전 글에도 남겼지만 #을 이용해 제목 설정해주시면 좋겠습니다!
혹시 원하신다면 앞 편과 하나의 글로 묶어서 줄글로 늘여써도 좋을 것 같습니다!
수고하셨어요 :)

2023-05-10 02:43 UTC, xMHW commented on blog/2023/05-05-minseong/index.md
> +# IaC To Terraform
@JeukHwang 제목 추가하고 하나의 글로 합쳤습니당

2023-05-14 08:30 UTC, sboh1214 submitted a review, later dismissed
LGTM

2023-08-18 03:11 UTC, sboh1214 approved these changes
LGTM

2023-08-18 03:12 UTC, merged