blog: 05-05-default
sparcs-kaist/sparcs.org-v3 pull request #38
Opened 2023-05-05 12:21 UTC by skykhs3

기술 블로그 입니다.

2023-05-06 12:15 UTC, sboh1214 requested changes
수고하셨습니다~

2023-05-06 12:15 UTC, sboh1214 commented on blog/2023/05-05-default/index.md
> +slug: newara-default1
제목과 관련있는 slug로 변경해 주세요.
ex) `flutter-vs-react-native`

2023-05-07 17:57 UTC, sboh1214 approved these changes
LGTM

2023-05-08 05:01 UTC, JeukHwang reviewed
그래프까지 넣어서 글을 쓰시다니! 정말 수고하셨습니다 :)
혹시 직접 제작하신 것이라면 vs.png를 화질이 더 높은 것으로 바꿀 수 있을까요?

2023-08-18 03:20 UTC, sboh1214 approved these changes
LGTM

2023-08-18 18:54 UTC, merged